remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: Rutvik Kulkarni
description: Machine Learning Developer
show_downloads: false
theme: jekyll-theme-hacker

github:
  repository_url: https://github.com/Rutvik1728
